### ISSUE TITLE
Doubled Up Messages

### ISSUE THREAD

**Issue by PhoenixICE** [NitroXenon/LineThrift#1]
Hey,

Not sure if you are still working on this or even looking at it, but when using the .sendMessage method for some reason some of my text doubles up, can you think of any reason why?

http://imgur.com/4qAXfRu

It uses the api.OnReceiveMessage += api_OnReceiveMessage; event hook to achieve this which is created by the library -> https://github.com/NitroXenon/LineApi.NET

-Icy

		public static TalkService.Client Client { get; set; }
		public static void SendTextReal(string text, params object[] param)
		{
			if (param == null)
				param = new object[0];			
			string message = string.Format(text, param).Replace("\r", " ").Replace("\n", " ").Replace("  ", " ").Trim();
				
			IcyLineBot.Client.sendMessage(0, new Message() { To = IcyLineBot.Group.Id, Text = message }); //(SendType.Message, data.Channel, color + message);			
		}

**Comment by NitroXenon** [comment]
I'll test for it later. Maybe Naver changed the thrift file.

So you can try to re-auth and test to see whether this issue will happen again :)

**Comment by NitroXenon** [comment]
hey you better/can try this library :
https://github.com/Banandana/LineSharp

This repo will be under maintenance in a while since the above library is better than mine :/

**Comment by PhoenixICE** [comment]
I think I tried that library and it didn't let me login, so I tried yours, so far yours is the only one that has worked as an implementation, but if you aren't going to be working on this repo I'll see if I can figure out what is wrong with his version.

**Comment by PhoenixICE** [comment]
Hmm...just tried the other API, its completely non-functional, even after fixing the login many other issues occurred, is there no way you'd look into the issue?

**Comment by Banandana** [comment]
rip

I can look into login shit for you, I'm on my way out the door at work and will check it out at home.

**Comment by Banandana** [comment]
It's probably the exponent in the RSA encryption fucking up.
